- name: RHSM Subscribe | check if {{ satellite_fqdn }} ins in rhsm.conf
  command: grep {{ satellite_fqdn }} /etc/rhsm/rhsm.conf
  register: checkrhsm
  check_mode: no
  ignore_errors: yes
  changed_when: no


- name: RHSM Subscribe | remove old subscription
  redhat_subscription:
    state: absent
  when: checkrhsm.rc != 0

- name: RHSM Subscribe | remove old rpms from Satellite 6
  yum:
    name:
      - katello-ca-consumer-*.noarch
    state: absent
  when: checkrhsm.rc != 0

- name: Install local Katello-ca RPM
  package:
    name:  https://{{ satellite_fqdn }}/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
  when: checkrhsm.rc != 0

- name: Using an Activation Key for register to  {{ satellite_fqdn }}
  redhat_subscription:
    state: present
    activationkey: "{{ capsule_ak }}"
    org_id: "{{ satellite_org }}"
    pool: '^(Red Hat Satellite Infrastructure Subscription)$'
  when: checkrhsm.rc != 0