- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled
    
- name: Enable a RHSM repository
  rhsm_repository:
    name: 
       - rhel-8-for-x86_64-baseos-rpms
       - rhel-8-for-x86_64-appstream-rpms
       - satellite-capsule-6.14-for-rhel-8-x86_64-rpms
       - satellite-maintenance-6.14-for-rhel-8-x86_64-rpms


- name: enable Satellite modules
  shell: dnf module enable satellite-capsule:el8
