- name: install | install satellite package
  package:
    name: "satellite-capsule"
    state: present

- name: install | Checking if /var/lib/pulp is owned by apache
  file:
    path: /var/lib/pulp
    owner: apache
    group: apache
    mode: '0755'
