- name: run the capsule installer
  shell: >-
    satellite-installer
    --scenario capsule
    --foreman-proxy-register-in-foreman "true"
    --foreman-proxy-foreman-base-url "https://{{ satellite_fqdn }}"
    --foreman-proxy-trusted-hosts "{{ satellite_fqdn }}"
    --foreman-proxy-trusted-hosts "{{ ansible_fqdn }}"
    --foreman-proxy-oauth-consumer-key "{{ foreman_proxy_oauth_consumer_key }}"
    --foreman-proxy-oauth-consumer-secret "{{ foreman_proxy_oauth_consumer_secret }}"
    --certs-tar-file "/root/capsule-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}-capsule-certs.tar"
  register: capsule_installer_output
  when:
    -  not (existing_tarball.stat.exists)
