---
- name: Main | Register to Satellite
  import_tasks: 1_rhsm.yml

- name: Main | Enable Repos
  import_tasks: 2_enable_repos.yml

- name: Main | Patch system
  import_tasks: 3_patch.yml

- name: Main | Configure Storage
  import_tasks: 4_configure_storage.yml
  
- name: Main | Install Satellite Capsule
  import_tasks: 5_install_package capsule.yml

- name: Main | Add host entry in /etc/hosts
  import_tasks: 6_dns_config.yml

- name: Main | Create custome certs
  import_tasks: 7_prep-custom-certs.yml
  delegate_to: "{{ satellite_fqdn }}"
  throttle: 1

- name: Main | Generate Capsule Install certificats
  import_tasks: 8_generate_cap_cert.yml

- name: Main | Install Satellite Capsule server
  import_tasks: 9_install_capsule.yml